import { useState } from 'react'
import { useNavigate } from 'react-router-dom'
import { ShieldAlert, ArrowRight, Activity, Smile, BookOpen } from 'lucide-react'
import ResearchNote from '../../components/ResearchNote'

export default function RecoveryPage() {
  const navigate = useNavigate()
  
  // Read dynamic failure profile generated by the Triple-A review page
  const activeAppraisal = localStorage.getItem('active_failure_appraisal') || 'strategy'
  
  // Recovery Interface State
  const [recoveryStep, setRecoveryStep] = useState(1) // 1: Protocol Blueprint, 2: The Rise Ritual
  const [lesson, setLesson] = useState('')
  const [tinyIfThen, setTinyIfThen] = useState('')
  const [identityUpdate, setIdentityUpdate] = useState('I am becoming highly resilient through adaptive strategy shifts.')

  const handleExecuteProtocol = () => {
    setRecoveryStep(2)
  }

  const handleCompleteRise = () => {
    if (!lesson || !tinyIfThen) return

    // Update the system altitude loop counter safely inside cache
    const currentAltitude = Number(localStorage.getItem('loop_altitude') || '0')
    const updatedAltitude = currentAltitude + 1
    localStorage.setItem('loop_altitude', updatedAltitude.toString())

    // Append localized lessons into a simulated structural array log
    const historicLessons = JSON.parse(localStorage.getItem('lesson_library') || '[]')
    historicLessons.push({ lesson, tinyIfThen, timestamp: new Date().toISOString() })
    localStorage.setItem('lesson_library', JSON.stringify(historicLessons))

    // Clear temporary diagnostic blockers and push clean states back to home base
    localStorage.removeItem('active_failure_appraisal')
    navigate('/dashboard')
  }

  return (
    <div className="min-h-screen bg-[#FAF9F6] text-[#1C1917] px-6 py-12 flex flex-col justify-center">
      <div className="max-w-xl w-full mx-auto bg-white border border-[#E8E4DC] rounded-2xl p-8 shadow-sm">
        
        {/* ── STEP 1: TARGETED RECOVERY PROTOCOL DISPLAY ── */}
        {recoveryStep === 1 && (
          <div className="space-y-6 animate-fade-in">
            <div className="flex items-center gap-2">
              <ShieldAlert className="text-[#991B1B]" size={20} />
              <span className="text-[10px] font-bold tracking-widest text-[#991B1B] uppercase">Causal Correction Loop [Level 7]</span>
            </div>

            {/* TYPE 1: STRATEGY FAILURE INTERVENTION */}
            {activeAppraisal === 'strategy' && (
              <div className="space-y-4">
                <h2 className="text-2xl font-serif font-bold text-[#1C1917]">You showed up. The method was wrong. [Strategy Failure]</h2>
                <p className="text-xs text-[#78716C] leading-relaxed">
                  Your effort was real, but your execution framework contains operational mistakes. This is raw objective data, not a sign of your capability.
                </p>
                <div className="p-4 bg-[#FAF9F6] border border-[#E8E4DC] rounded-xl text-xs space-y-2 text-[#78716C]">
                  <p className="font-bold text-[#1C1917]">Active Recovery Actions Required:</p>
                  <p>1. Isolate the broken operational assumption in your setup workflow.</p>
                  <p>2. Swap the method approach completely for the upcoming 14-day loop cycle.</p>
                </div>
              </div>
            )}

            {/* TYPE 2: CAPACITY FAILURE INTERVENTION */}
            {activeAppraisal === 'capacity' && (
              <div className="space-y-4">
                <h2 className="text-2xl font-serif font-bold text-[#1C1917]">A genuine skill gap exists right now. [Capacity Bounds]</h2>
                <p className="text-xs text-[#78716C] leading-relaxed">
                  This isn't a character flaw—it's simply an honest structural map indicating where your learning needs to happen.
                </p>
                <div className="p-4 bg-[#FAF9F6] border border-[#E8E4DC] rounded-xl text-xs space-y-2 text-[#78716C]">
                  <p className="font-bold text-[#1C1917]">Active Success Ladder Actions Required:</p>
                  <p>1. Lower the task's required velocity down to your absolute execution floor.</p>
                  <p>2. Focus exclusively on locking in simple, micro-wins over the next 7 days.</p>
                </div>
              </div>
            )}

            {/* FALLBACK/EFFORT PROFILE INTERVENTION */}
            {(activeAppraisal === 'effort' || activeAppraisal === 'circumstance') && (
              <div className="space-y-4">
                <h2 className="text-2xl font-serif font-bold text-[#1C1917]">The input variables fluctuated. [Operational Disruption]</h2>
                <p className="text-xs text-[#78716C] leading-relaxed">
                  The goal parameters are correct, but the physical follow-through was interrupted. We will re-anchor your behavioral prompts.
                </p>
                <div className="p-4 bg-[#FAF9F6] border border-[#E8E4DC] rounded-xl text-xs space-y-2 text-[#78716C]">
                  <p className="font-bold text-[#1C1917]">Active Prompt Actions Required:</p>
                  <p>1. Re-evaluate your Fogg behavior design anchor points.</p>
                  <p>2. Increase the visibility of your accountability partner updates.</p>
                </div>
              </div>
            )}

            <button
              onClick={handleExecuteProtocol}
              className="w-full flex items-center justify-center gap-2 rounded-xl py-3.5 px-6 text-sm font-semibold bg-[#991B1B] text-white hover:opacity-95 transition-all"
            >
              Initialize The Rise Ritual
              <ArrowRight size={16} />
            </button>
          </div>
        )}

        {/* ── STEP 2: THE UNIVERSAL RISE RITUAL WORKSPACE ── */}
        {recoveryStep === 2 && (
          <div className="space-y-6 animate-fade-in">
            <div>
              <div className="flex items-center gap-2 mb-1">
                <Activity className="text-[#166534]" size={18} />
                <span className="text-[10px] font-bold tracking-widest text-[#166534] uppercase">End of Recovery Session · Rise</span>
              </div>
              <h2 className="text-2xl font-serif font-bold">Document the operational iteration</h2>
              <p className="text-xs text-[#78716C] mt-1">
                This is how momentum rebuilds—step by step, backed by real data.
              </p>
              <p className="font-sinhala text-[12px] text-[#A8A29E] mt-1">
                සිංහල: සිදු වූ දෙයින් උගත් පාඩම් එකතු කර, බිඳ වැටුණු තැන්වලින් නැවත නැඟී සිටීමට අවශ්‍ය කුඩාම පියවර මෙහිදී සටහන් කරමු.
              </p>
            </div>

            <div className="space-y-4 pt-2">
              <div className="space-y-1">
                <label className="block text-xs font-semibold text-[#1C1917]">1. Speak the Lesson: What do you know now that you didn't before?</label>
                <input 
                  type="text" value={lesson} onChange={e => setLesson(e.target.value)}
                  placeholder="e.g., Blockers aren't personal flaws; my morning routine prompt was misaligned."
                  className="w-full p-3 text-xs bg-[#FAF9F6] border border-[#E8E4DC] rounded-xl focus:outline-none focus:border-[#166534]"
                />
              </div>

              <div className="space-y-1">
                <label className="block text-xs font-semibold text-[#1C1917]">2. Micro If-Then Blueprint: Write tomorrow's first tiny action plan</label>
                <input 
                  type="text" value={tinyIfThen} onChange={e => setTinyIfThen(e.target.value)}
                  placeholder="e.g., If it is 7:00 AM, then I will open my documentation file and write exactly one heading line."
                  className="w-full p-3 text-xs bg-[#FAF9F6] border border-[#E8E4DC] rounded-xl focus:outline-none focus:border-[#166534]"
                />
                <span className="text-[10px] text-[#A8A29E] block">Make it small enough that you are 100% certain you will do it.</span>
              </div>

              <div className="space-y-1">
                <label className="block text-xs font-semibold text-[#1C1917]">3. Iterated Present Identity Statement</label>
                <input 
                  type="text" value={identityUpdate} onChange={e => setIdentityUpdate(e.target.value)}
                  className="w-full p-3 text-xs bg-[#FAF9F6] border border-[#E8E4DC] rounded-xl focus:outline-none focus:border-[#166534]"
                />
              </div>
            </div>

            <button
              onClick={handleCompleteRise}
              disabled={!lesson || !tinyIfThen}
              className="w-full flex items-center justify-center gap-2 rounded-xl py-3.5 px-6 text-sm font-semibold bg-[#1C1917] text-white transition-all disabled:opacity-30 disabled:cursor-not-allowed"
            >
              Increment Loop Altitude & Rise
              <ArrowRight size={16} />
            </button>
          </div>
        )}

      </div>
    </div>
  )
}